### ISSUE TITLE
Usage of a transpiler

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/nodecloud#10]
Basic use of a transpiler would be to convert one version of JavaScript to another version of JavaScript. This will provide few benefits and drawbacks as well.

**Pros:**
Using a transpiler bleeding edge JavaScript features can be used. eg : `async` & `await` in ES7.

**Cons:**
Using a transpiler every time there needs to be a build process that should run in order to convert JavaScript to a certain version. eg : `ES6` to `ES5`. This will have a certain cost.

[Babel](https://babeljs.io/) would be the best option if the decision is made to go ahead with a transpiler.

**Comment by rajikaimal** [comment]
Therefore JavaScript version for the library implementation should be decided. eg: `ES5` / `ES6`.

**Comment by rehrumesh** [comment]
We will not use a transpiler
