### ISSUE TITLE
Add support for Google Cloud Storage

### ISSUE THREAD

**Issue by rehrumesh** [scorelab/nodecloud#18]

**Comment by rajikaimal** [comment]
Google persistent disk can be considered as the equivalent of AWS EBS.

**Block Storage**

- [ ] Create PD
- [ ] Create snapshot 
- [ ] Delete PD
- [ ] Check if disk exists
- [ ] Get a disk if exists
- [ ] Get metadata
- [ ] Get a reference to a snapshot from this disk

**Comment by rajikaimal** [comment]
We'll add features listed here and equivalents in AWS for now ? @rehrumesh 

#17
