### ISSUE TITLE
Design a logo for NodeCloud

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/nodecloud#44]
A logo should be designed for NodeCloud library. It should reflect the functionality of NodeCloud at a glance.

Logo should be delivered in `.png` and `.svg` formats.

**Comment by lakindu95** [comment]
HI @rajikaimal ,

I have created a logo to NodeCloud. Hope this will meet the requirements

![nodecloud-logo](https://user-images.githubusercontent.com/19621902/32136358-f39bd0d0-bc29-11e7-9cee-c1e1fc208870.png)

**Comment by rajikaimal** [comment]
Hi !,

This looks good, any thoughts @rehrumesh ?

**Comment by rehrumesh** [comment]
This is good. I'd like if we can change 'js' part into something else..

**Comment by lakindu95** [comment]
What if we add node logo in the middle? any other suggestions? 
@rehrumesh @rajikaimal

**Comment by rehrumesh** [comment]
surprise us with different options 👍

**Comment by rajikaimal** [comment]
Yeah, maybe adding the logo will make a difference. Either way we'll see few mock ups and select the best one. 😄

**Comment by lakindu95** [comment]
Any suggestions guys? 

![logo](https://user-images.githubusercontent.com/19621902/32183214-b3f2571a-bdbe-11e7-8786-5225b454666e.png)
![logo2](https://user-images.githubusercontent.com/19621902/32183225-baeb0620-bdbe-11e7-97c1-dfadcc028857.png)
