### ISSUE TITLE
Project tooling

### ISSUE THREAD

**Issue by rajikaimal** [scorelab/nodecloud#8]
From the beginning of the project, it would be beneficial if a proper JavaScript tooling set is used. Following are the identified areas where different tools can be added to improve the developer experience and the overall code quality of the project.

- Linting.

  [ESLint](http://eslint.org/) :mag: 

- Making coding standards consistent between different IDEs/Text Editors.

  [editorconfig](http://editorconfig.org/) :octocat: 

- Build system.

  [Gulp](http://gulpjs.com/) :construction: 

- Unit testing.

  [Ava](https:/ava.li) OR [Jest](https://facebook.github.io/jest/) :rocket:

**Comment by rehrumesh** [comment]
👍 for everything except Unit testing. Lets move ahead with Mocha

**Comment by rajikaimal** [comment]
Got it
